In [1]:
import numpy as np
import os

x = np.arange(16).reshape(4,4)

print("Array:")
print(x)

header = 'C1 C2 C3 C4'
np.savetxt('7_array.txt', x, fmt="%d", header=header)

print("\nAfter loading, content of the text file:")
print(np.loadtxt('7_array.txt'))

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After loading, content of the text file:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
